### ISSUE TITLE
Errors and Warnings logged as Trace

### ISSUE THREAD

**Issue by ifle** [serilog/serilog-sinks-applicationinsights#65] opened 2018-07-19 08:12 UTC
I can see all warnings and errors show up as Trace in AI instead of exception or warnings. I use .Net 4.6.2 application and Microsoft.Extensions.Logging

As we can see the Severity Level interpreted as regular Trace property.

![image](https://user-images.githubusercontent.com/1140474/42929974-55da00f2-8b44-11e8-8a1c-f6d8478297fe.png)

Can it be configured?

**Comment by aloneguid** [comment] 2019-02-05 00:07
This is by design - by default everything is logged as trace with appropriate severity level which is correct (set to warning in your screenshot). Exceptions are always logged as AI exceptions. If you would like to customise this behavior there is an overload sample in readme you can follow.

Closing this issue but please kindly reopen if you need any help with configuration.

**Closed by aloneguid** 2019-02-05 00:07 UTC
