### ISSUE TITLE
The call is ambiguous between the following methods or properties

### ISSUE THREAD

**Issue by abergs** [serilog/serilog-sinks-applicationinsights#93] opened 2019-02-12 12:38 UTC
CS0121	The call is ambiguous between the following methods or properties: 'LoggerConfigurationApplicationInsightsExtensions.ApplicationInsights(LoggerSinkConfiguration, TelemetryClient, Func<LogEvent, IFormatProvider, ITelemetry>, LogEventLevel, IFormatProvider)' and 'LoggerConfigurationApplicationInsightsExtensions.ApplicationInsights(LoggerSinkConfiguration, TelemetryClient, Func<LogEvent, IFormatProvider, IEnumerable<ITelemetry>>, LogEventLevel, IFormatProvider)'

I upgraded the nuget and I am now receiving this. Any advice?

**Comment by mikebeckdev** [comment] 2019-02-13 17:22
Might be worth adding the issue isn't fixed by updating the method signature to include ITelemetry, it then gives another error (cannot convert from method group to Func) and the visual studio "fix" for that is to autogenerate another function without the ITelemetry, which returns you to the same error mentioned above...

**Comment by jondmcelroy** [comment] 2019-02-13 20:36
Looks like 2.6.1 is the last version that works before this was broken.

**Comment by aloneguid** [comment] 2019-02-13 21:07
I can see it - since we've added an overload which now accepts either `Func<LogEvent, IFormatProvider, ITelemetry>` or `Func<LogEvent, IFormatProvider, IEnumerable<ITelemetry>>`, C# compiler cannot distinguish between two unless you specify it explicitly.

The current workaround is to give a hint to the compiler, i.e. instead of `.WriteTo.ApplicationInsights(tc, conversion)` write `.WriteTo.ApplicationInsights(tc, (Func<LogEvent, IFormatProvider, ITelemetry>)conversion)`.

**Comment by aloneguid** [comment] 2019-02-13 21:45
This is fixed in v2.6.4, let me know if you still have issues.

**Closed** 2019-02-13 21:55 UTC
