### ISSUE TITLE
LogLevel, RenderedMessage and MessageTemplate vanished again...

### ISSUE THREAD

**Issue by Powerz** [serilog/serilog-sinks-applicationinsights#100] opened 2019-02-25 06:19 UTC
Hi,

(Version: 3.0.1)

What's happening: **LogLevel**, **RenderedMessage** and **MessageTemplate** disappeared from CustomeDimensions. Again.

Sometime ago it was broken in 2.6.1, then I pull requested the fix and everything was fine until v3...

These 3 properties contain vital information, so, in my opinion, this is a critical bug which should be fixed ASAP. Please let me know if you want me to PR this, I don't mind doing that as long as we get the working version soon enough.

And probably, it's time to unit test it in order not to break it later on ;)

**Comment by aloneguid** [comment] 2019-02-25 08:36
It's actually not a bug and it's not broken. LogLevel is excluded *by default* because AI already has built-in property for log level which is populated. RenderedMessage is excluded *by default* because AI already has message property, also populated. MessageTemplate is not there by popular demands.

In general, duplicating information in customDimension has no value whatsoever, and because in AI you are charged for amount of traffic from the application, it makes perfect sense to keep the message small. You can always customise logging if you need it, but for a generic use case sending more for no reason is a bad practice.

**Comment by Powerz** [comment] 2019-02-25 09:48
Hi @aloneguid ,

Before posting this I'd checked the AI custom events (not traces) and didn't find **LogLevel** at all (it is there for Traces as a numeric value though). 

**MessageTemplate** matches "name" for custom events and seems to be missing for traces.

**RenderedMessage** is missing for custom events and matches "message" for traces.

>MessageTemplate is not there by popular demands

You know best, but I found this which looks like the opposite: https://github.com/serilog/serilog-sinks-applicationinsights/issues/95

Could you please suggest where I can find LogLevel and RenderedMessage in case of using custom events?

**Comment by aloneguid** [comment] 2019-02-25 16:38
Hi @Powerz it's best if you customise logging for specific project's needs. The default configuration suits the majority of use cases I've seen here in open issues. I understand it may not be perfect for everyone, hence customisability is available. Readme also describes which properties are included in events and traces, and this sink logs exactly them, therefore I don't think "missing" properties fall under "bugs" category in any way. 

I think the idea about more unit tests is great - when I picked up this project there were none and adding just a few has already improved an understanding how it should work. I'd appreciate your help in doing this.

**Comment by aloneguid** [comment] 2019-02-27 14:29
Closing for now, please feel free to reopen.

**Closed by aloneguid** 2019-02-27 14:29 UTC

**Comment by Powerz** [comment] 2019-02-27 15:41
Hi @aloneguid ,

Custom message converter will do :)

Btw, thank you for working on that project! 👍
